// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Raphael Olaiyapo",
            "url": "https://archdemy.netlify.app/",
            "email": "raphael.tunji@yahoo.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/BillCategories": {
            "post": {
                "description": "Get bill categories.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Flutterwave"
                ],
                "summary": "Bill categories",
                "parameters": [
                    {
                        "description": "Bill Categories",
                        "name": "Todo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Model.GetBillsCatPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful response",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/Todos": {
            "get": {
                "description": "Get a list of all todos.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todos"
                ],
                "summary": "Get a list of todos",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/Model.Todo"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Add a todo to list of todos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todos"
                ],
                "summary": "Add a todo",
                "parameters": [
                    {
                        "description": "Add Todo",
                        "name": "Todo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Model.AddTodoDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.Todo"
                        }
                    }
                }
            }
        },
        "/Todos/{id}": {
            "get": {
                "description": "Get a todo from list of todos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todos"
                ],
                "summary": "Get a todo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Model.Todo"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a todo from the list of todos.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Todos"
                ],
                "summary": "Delete a todo",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Todo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Model.AddTodoDto": {
            "type": "object",
            "required": [
                "item",
                "owner"
            ],
            "properties": {
                "completed": {
                    "type": "boolean"
                },
                "item": {
                    "description": "custom validation",
                    "type": "string"
                },
                "owner": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                }
            }
        },
        "Model.GetBillsCatPayload": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "string"
                },
                "queryParam": {
                    "type": "string"
                }
            }
        },
        "Model.Todo": {
            "type": "object",
            "required": [
                "item",
                "owner"
            ],
            "properties": {
                "completed": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "item": {
                    "description": "custom validation",
                    "type": "string"
                },
                "owner": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 2
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Todo API",
	Description:      "This is a Todo CRUD application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
