basePath: /api/v1
definitions:
  Model.AddTodoDto:
    properties:
      completed:
        type: boolean
      item:
        description: custom validation
        type: string
      owner:
        maxLength: 100
        minLength: 2
        type: string
    required:
    - item
    - owner
    type: object
  Model.GetBillsCatPayload:
    properties:
      index:
        type: string
      queryParam:
        type: string
    type: object
  Model.Todo:
    properties:
      completed:
        type: boolean
      id:
        type: string
      item:
        description: custom validation
        type: string
      owner:
        maxLength: 100
        minLength: 2
        type: string
    required:
    - item
    - owner
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: raphael.tunji@yahoo.com
    name: Raphael Olaiyapo
    url: https://archdemy.netlify.app/
  description: This is a Todo CRUD application.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Todo API
  version: "1.0"
paths:
  /BillCategories:
    post:
      consumes:
      - application/json
      description: Get bill categories.
      parameters:
      - description: Bill Categories
        in: body
        name: Todo
        required: true
        schema:
          $ref: '#/definitions/Model.GetBillsCatPayload'
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            type: object
      summary: Bill categories
      tags:
      - Flutterwave
  /Todos:
    get:
      description: Get a list of all todos.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/Model.Todo'
            type: array
      summary: Get a list of todos
      tags:
      - Todos
    post:
      consumes:
      - application/json
      description: Add a todo to list of todos.
      parameters:
      - description: Add Todo
        in: body
        name: Todo
        required: true
        schema:
          $ref: '#/definitions/Model.AddTodoDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Model.Todo'
      summary: Add a todo
      tags:
      - Todos
  /Todos/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a todo from the list of todos.
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Delete a todo
      tags:
      - Todos
    get:
      consumes:
      - application/json
      description: Get a todo from list of todos.
      parameters:
      - description: Todo ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Model.Todo'
      summary: Get a todo
      tags:
      - Todos
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
